"""init

Revision ID: 13ad1ed464ef
Revises:
Create Date: 2025-05-11 23:19:36.543206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13ad1ed464ef"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column(
            "tg_user_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("is_subscription", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("tg_user_id"),
    )
    op.create_table(
        "motivating_phrases",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("phrase", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "purpose_countdown",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("sent_notification_today", sa.Boolean(), nullable=True),
        sa.Column("tg_user_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tg_user_id"],
            ["clients.tg_user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purpose_countdown")
    op.drop_table("motivating_phrases")
    op.drop_table("clients")
    # ### end Alembic commands ###
